### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by MeycL** [zjukg/Ruleformer#1]
Thank you very much for your work open source. I would like to ask about the data preprocessing there, for FB15K-237 dataset jump=1, for wn18rr dataset jump=2, for umls dataset jump=3, is the fact as I understand it? I am looking forward to your answer.

**Comment by oier991215** [comment]
Hello, for the FB15K-237 dataset, what is the jump setting to reproduce the experimental results？

**Comment by yep96** [comment]
Thanks for your interest in our work! The hyperparameter `jump` corresponds to the rule length `T` in the paper. For specific data, please refer to the `T=` in parentheses after the model name in the experimental results table.
